# File: .github/workflows/publish.yml
name: Deploy to dokploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  NODE_ENV: production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node
        with:
          node-env: ${{ env.NODE_ENV }}
      - name: Run tests
        run: npx vitest --coverage.enabled true
      - name: Report converage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
